-- XpressBees Profitability AI Agent - Database Setup
-- Run this first to create the database, schemas, warehouse, and stage

CREATE DATABASE IF NOT EXISTS XPRESSBEES_PROFITABILITY;

USE DATABASE XPRESSBEES_PROFITABILITY;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS SEMANTIC_MODELS;
CREATE SCHEMA IF NOT EXISTS AGENTS;

CREATE WAREHOUSE IF NOT EXISTS SNOW_INTELLIGENCE_DEMO_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

USE WAREHOUSE SNOW_INTELLIGENCE_DEMO_WH;

CREATE STAGE IF NOT EXISTS RAW.DATA_STAGE;

CREATE STAGE IF NOT EXISTS SEMANTIC_MODELS.SEMANTIC_STAGE;

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null', '#N/A')
  FIELD_DELIMITER = ','
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';
